### ISSUE TITLE
Make one sample demo using sdk

### ISSUE THREAD

**Issue by PPotlaACR** [stntz/Xamarin.ZoomBinding#1]
how to use in our project and namespaces

when i  install through nuget and build the project am getting below error

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Xamarin.Android.Zoom 1.0.0 is not compatible with monoandroid90 (MonoAndroid,Version=v9.0). Package Xamarin.Android.Zoom 1.0.0 supports: monoandroid10.0 (MonoAndroid,Version=v10.0)	ZoomForAndriod	C:\Users\prave\OneDrive\Desktop\ZoomForAndriod\ZoomForAndriod\ZoomForAndriod.csproj	1

**Comment by stntz** [comment]
Yes, I see that now. I had set the target to v10.0 only. Now changing to v9.0 and working on a quick sample

**Comment by stntz** [comment]
@PPotlaACR are you able to set your android version to 10.0 as the zoom sdk is minimum api 29.
I have now changed the target to 9.0 and added a very basic sample for iOS and Android.

Let me know if you have any more issue. I will now close this

**Comment by PPotlaACR** [comment]
Hi stntz  , let me know when will update in nuget. currently play store supporting android version 8.0 and above
