### ISSUE TITLE
iOS builds on physical device but not simulator

### ISSUE THREAD

**Issue by conor-codes** [stntz/Xamarin.ZoomBinding#10]
Hello, 

When building an app with the sdk installed for a physical device all works perfectly, on a simulator there is 17 linker errors, does the same happen for you and if so have you managed to resolve any of the linker errors?

Thanks

**Comment by stntz** [comment]
I only did a binding for the zoom sdk that supports only devices.
the sdk that supports simulator according to their docs will not be approved by Apple for the store.

[https://github.com/zoom/zoom-sdk-ios/releases](url)

**Comment by conor-codes** [comment]
Oh right , well that's fair enough thanks for the response
