### ISSUE TITLE
iOS App fails to build - Native Linking failed

### ISSUE THREAD

**Issue by kgbuddhima** [stntz/Xamarin.ZoomBinding#11]
I'm having following errors when building the iOS app

Native linking failed, undefined Objective-C class: MobileRTCAlternativeHost. The symbol '_OBJC_CLASS_$_MobileRTCAlternativeHost' could not be found in any of the libraries or frameworks linked with your application.

Native linking failed, undefined Objective-C class: MobileRTCBOCreator. The symbol '_OBJC_CLASS_$_MobileRTCBOCreator' could not be found in any of the libraries or frameworks linked with your application.

Native linking failed, undefined symbol: _kMeetingParam_IsAppShare. This symbol was referenced by the managed member Zoomios.Constants.kMeetingParam_IsAppShare. Please verify that all the necessary frameworks have been referenced and native libraries linked.

Here are the libraries I used..

Xamarin.Forms 4.5.0.495
Xamarin.iOS.Zoom 1.0.0
Xamarin.Essentials 1.3.1

I added the link skipping too. but still the problem exists.

![image](https://user-images.githubusercontent.com/14989528/85557527-78912c00-b645-11ea-854e-af123c85e2d3.png)

**Comment by conor-codes** [comment]
The binding doesn't work for simulators, only physical devices

**Comment by kgbuddhima** [comment]
> The binding doesn't work for simulators, only physical devices

So should I use this with a live device ?
Why can't I build the solution ?

**Comment by conor-codes** [comment]
If you have physical device it will compile, this is from the author of the package:

> I only did a binding for the zoom sdk that supports only devices.
> the sdk that supports simulator according to their docs will not be approved by Apple for the store.
> 
> https://github.com/zoom/zoom-sdk-ios/releases

If you look on the github release it states there is another package but it will get rejected from the app store if you use this one, but that allows simulators. For testing i assume.

> 
> The code in the "Source Code (zip)" is the device-only version. It only works on a real device. Please use this version if you would like to upload to the Apple App Store.
> The "ios-mobilertc-all-4.6.21666.0428-n.zip" is the "all" version that works on both real device and iOS simulator(x86_64, i386, etc.). Do not use this version to publish apps to App Store.

**Comment by kgbuddhima** [comment]
> If you have physical device it will compile, this is from the author of the package:
> 
> > I only did a binding for the zoom sdk that supports only devices.
> > the sdk that supports simulator according to their docs will not be approved by Apple for the store.
> > https://github.com/zoom/zoom-sdk-ios/releases
> 
> If you look on the github release it states there is another package but it will get rejected from the app store if you use this one, but that allows simulators. For testing i assume.
> 
> > The code in the "Source Code (zip)" is the device-only version. It only works on a real device. Please use this version if you would like to upload to the Apple App Store.
> > The "ios-mobilertc-all-4.6.21666.0428-n.zip" is the "all" version that works on both real device and iOS simulator(x86_64, i386, etc.). Do not use this version to publish apps to App Store.

I was able to run on a live device.
