### ISSUE TITLE
How do I override the back button?

### ISSUE THREAD

**Issue by patkozlowski** [stntz/Xamarin.ZoomBinding#13]
When joining the meeting how do I override the back button?  It just exits or minimizes the app currently.  Since the meeting activity isn't exposed from what I can see, I can't override the back button.

Thanks

**Comment by stntz** [comment]
Hi @patkozlowski , are you using the nuget package.. it might need an update to support overriding the metting activity.
if you clone the repo, you should have the activity exposed.
I will update the nuget package soon.

**Comment by patkozlowski** [comment]
I cloned the repo, and indeed it does have the meeting activity exposed.  I followed this from the zoom forum, and it works for anyone that wants to do so:

Create your own activity, for example, MyMeetingActivity
In config.xml, add the following:
<string name="zm_config_conf_activity">us.zoom.sdksample.MyMeetingActivity</string>
Declare the Activity in your AndroidManifest.xml
In your MyMeetingActivity class, extends MeetingActivity
public class MyMeetingActivity extends MeetingActivity {
...
}
Override the onBackPressed method:
@Override
    public void onBackPressed() {
 onClickLeave();
...
}
If you would like define other actions other than calling the leave meeting dialog, you can do whatever you prefer in this callback.

**Comment by stntz** [comment]
Thanks @patkozlowski I believe I have that working in a personal project that I use this for. Nuget update should be this weekend.

**Comment by patkozlowski** [comment]
@stntz  thanks for being so responsive, this is a huge undertaking that gives the xamarin community great value.  I've noticed a lot of my clients wanting something like this, and is a big win for all of us.  Thanks for this binding!!!
