### ISSUE TITLE
Error when build iOS

### ISSUE THREAD

**Issue by dothanhbinh41** [stntz/Xamarin.ZoomBinding#16]
Hi everyone!

I build Demo in iOS but something wrong there.

<img width="788" alt="Screen Shot 2020-09-01 at 3 28 26 PM" src="https://user-images.githubusercontent.com/25890459/91826676-1e759e00-ec68-11ea-8f30-03bb803af2f5.png">

Please help me fix this. 
Thanks

**Comment by stntz** [comment]
Hi @dothanhbinh41 , i see you closed the issue, you figured it out?

**Comment by gjhdigital** [comment]
Hello @stntz,
Great plugin! But I am having the similar issue when building on a Mac. It builds fine on a VS2019 on windows.
Hopefully you can point me in the right direction to fix this. Thanks in advance.
heres my output:

/Users/greg/Documents/Xamarin Projects/CoverBandDiaries/CoverBandDiaries/CoverBandDiaries.iOS/MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: MobileRTCAlternativeHost. The symbol '_OBJC_CLASS_$_MobileRTCAlternativeHost' could not be found in any of the libraries or frameworks linked with your application. (MT5211) (CoverBandDiaries.iOS)
/Users/greg/Documents/Xamarin Projects/CoverBandDiaries/CoverBandDiaries/CoverBandDiaries.iOS/MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: MobileRTCBOCreator. The symbol '_OBJC_CLASS_$_MobileRTCBOCreator' could not be found in any of the libraries or frameworks linked with your application. (MT5211) (CoverBandDiaries.iOS)
/Users/greg/Documents/Xamarin Projects/CoverBandDiaries/CoverBandDiaries/CoverBandDiaries.iOS/MTOUCH: Error MT5214: Native linking failed, undefined symbol: _kMeetingParam_IsAppShare. This symbol was referenced by the managed member Zoomios.Constants.kMeetingParam_IsAppShare. Please verify that all the necessary frameworks have been referenced and native libraries linked. (MT5214) (CoverBandDiaries.iOS)
/Users/greg/Documents/Xamarin Projects/CoverBandDiaries/CoverBandDiaries/CoverBandDiaries.iOS/MTOUCH: Error MT5214: Native linking failed, undefined symbol: _kMeetingParam_MeetingNumber. This symbol was referenced by the managed member Zoomios.Constants.kMeetingParam_MeetingNumber. Please verify that all the necessary frameworks have been referenced and native libraries linked. (MT5214) (CoverBandDiaries.iOS)
/Users/greg/Documents/Xamarin Projects/CoverBandDiaries/CoverBandDiaries/CoverBandDiaries.iOS/MTOUCH: Error MT5214: Native linking failed, undefined symbol: _kMeetingParam_MeetingPassword. This symbol was referenced by the managed member Zoomios.Constants.kMeetingParam_MeetingPassword. Please verify that all the necessary frameworks have been referenced and native libraries linked. (MT5214) (CoverBandDiaries.iOS)
/Users/greg/Documents/Xamarin Projects/CoverBandDiaries/CoverBandDiaries/CoverBandDiaries.iOS/MTOUCH: Error MT5214: Native linking failed, undefined symbol: _kMeetingParam_NoAudio. This symbol was referenced by the managed member Zoomios.Constants.kMeetingParam_NoAudio. Please verify that all the necessary frameworks have been referenced and native libraries linked. (MT5214) (CoverBandDiaries.iOS)
/Users/greg/Documents/Xamarin Projects/CoverBandDiaries/CoverBandDiaries/CoverBandDiaries.iOS/MTOUCH: Error MT5214: Native linking failed, undefined symbol: _kMeetingParam_NoVideo. This symbol was referenced by the managed member Zoomios.Constants.kMeetingParam_NoVideo. Please verify that all the necessary frameworks have been referenced and native libraries linked. (MT5214) (CoverBandDiaries.iOS)
/Users/greg/Documents/Xamarin Projects/CoverBandDiaries/CoverBandDiaries/CoverBandDiaries.iOS/MTOUCH: Error MT5214: Native linking failed, undefined symbol: _kMeetingParam_ParticipantID. This symbol was referenced by the managed member Zoomios.Constants.kMeetingParam_ParticipantID. Please verify that all the necessary frameworks have been referenced and native libraries linked. (MT5214) (CoverBandDiaries.iOS)
/Users/greg/Documents/Xamarin Projects/CoverBandDiaries/CoverBandDiaries/CoverBandDiaries.iOS/MTOUCH: Error MT5214: Native linking failed, undefined symbol: _kMeetingParam_UserID. This symbol was referenced by the managed member Zoomios.Constants.kMeetingParam_UserID. Please verify that all the necessary frameworks have been referenced and native libraries linked. (MT5214) (CoverBandDiaries.iOS)
/Users/greg/Documents/Xamarin Projects/CoverBandDiaries/CoverBandDiaries/CoverBandDiaries.iOS/MTOUCH: Error MT5214: Native linking failed, undefined symbol: _kMeetingParam_UserToken. This symbol was referenced by the managed member Zoomios.Constants.kMeetingParam_UserToken. Please verify that all the necessary frameworks have been referenced and native libraries linked. (MT5214) (CoverBandDiaries.iOS)
/Users/greg/Documents/Xamarin Projects/CoverBandDiaries/CoverBandDiaries/CoverBandDiaries.iOS/MTOUCH: Error MT5214: Native linking failed, undefined symbol: _kMeetingParam_UserType. This symbol was referenced by the managed member Zoomios.Constants.kMeetingParam_UserType. Please verify that all the necessary frameworks have been referenced and native libraries linked. (MT5214) (CoverBandDiaries.iOS)
/Users/greg/Documents/Xamarin Projects/CoverBandDiaries/CoverBandDiaries/CoverBandDiaries.iOS/MTOUCH: Error MT5214: Native linking failed, undefined symbol: _kMeetingParam_Username. This symbol was referenced by the managed member Zoomios.Constants.kMeetingParam_Username. Please verify that all the necessary frameworks have been referenced and native libraries linked. (MT5214) (CoverBandDiaries.iOS)
/Users/greg/Documents/Xamarin Projects/CoverBandDiaries/CoverBandDiaries/CoverBandDiaries.iOS/MTOUCH: Error MT5214: Native linking failed, undefined symbol: _kMeetingParam_VanityID. This symbol was referenced by the managed member Zoomios.Constants.kMeetingParam_VanityID. Please verify that all the necessary frameworks have been referenced and native libraries linked. (MT5214) (CoverBandDiaries.iOS)
/Users/greg/Documents/Xamarin Projects/CoverBandDiaries/CoverBandDiaries/CoverBandDiaries.iOS/MTOUCH: Error MT5214: Native linking failed, undefined symbol: _kMeetingParam_WebinarToken. This symbol was referenced by the managed member Zoomios.Constants.kMeetingParam_WebinarToken. Please verify that all the necessary frameworks have been referenced and native libraries linked. (MT5214) (CoverBandDiaries.iOS)
/Users/greg/Documents/Xamarin Projects/CoverBandDiaries/CoverBandDiaries/CoverBandDiaries.iOS/MTOUCH: Error MT5202: Native linking failed. Please review the build log. (MT5202) (CoverBandDiaries.iOS)
/Users/greg/Documents/Xamarin Projects/CoverBandDiaries/CoverBandDiaries/CoverBandDiaries.iOS/clang: Error: linker command failed with exit code 1 (use -v to see invocation) (CoverBandDiaries.iOS)
