### ISSUE TITLE
Fails to initialize for Android

### ISSUE THREAD

**Issue by gjhdigital** [stntz/Xamarin.ZoomBinding#19]
Hello, I can initialize fine with iOS but Android wont. Any guidance would be greatly appreciated.
The OnZoomSDKInitializeResult returns these values.
p0 = 3 and p1 = 5003

public void OnZoomSDKInitializeResult(int p0, int p1)
        {
            Console.WriteLine($"Authentication Status: {p0} - {p1}");
        }

My initParams are
var zoomInitParams = new ZoomSDKInitParams
            {
                AppKey = appKey,
                AppSecret = appSecret,
                EnableLog = true,
                LogSize = 50,
                Domain= "zoom.us",
                VideoRawDataMemoryMode = ZoomSDKRawDataMemoryMode.ZoomSDKRawDataMemoryModeStack
            };
            zoomSDK.Initialize(Android.App.Application.Context, this, zoomInitParams);

**Comment by stntz** [comment]
HI @gjhdigital 

This is the link for zoom error codes, [https://marketplace.zoom.us/docs/sdk/native-sdks/android/resource/error-codes](url)

It's saying Zoom server is currently not available..

**Comment by gjhdigital** [comment]
great thank you!
