### ISSUE TITLE
Build error in Android on release mode

### ISSUE THREAD

**Issue by PPotlaACR** [stntz/Xamarin.ZoomBinding#2]
Hi Stntz,
       I am getting an error in Andriod on release mode. find the error in the attachment below. 
though I kept "Java Max Heap Size: 1G " still It is showing the same error. and also the app size too large.

Thanks in advance

![Screenshot (2)](https://user-images.githubusercontent.com/43574666/82157674-9af29580-98a0-11ea-95f7-0480100df9d4.png)

**Comment by stntz** [comment]
Is this only in release mode? 
Also can you make sure the dll built by the CommonLib and MobileRtc_Droid is referenced in the Android project and MobileRTC_iOS in the iOS demo project. 
You might need to build the binding project in release mode before you run your app in release

**Comment by stntz** [comment]
Also can you set the link tool on android in release to r8 ![image](https://user-images.githubusercontent.com/12134684/82158358-42f76700-987f-11ea-90c2-f2bb03306043.jpeg)

**Comment by PPotlaACR** [comment]
Yes getting error in release mode only. Not in debug mode. In zoom.andriod project dll reference is took form nuget. See attachment below 
![IMG_20200518_012522](https://user-images.githubusercontent.com/43574666/82158620-a6e15600-98a6-11ea-8db7-83cebc090bcb.png)

**Comment by stntz** [comment]
I have just tried the project(android) as is against the nuget package and it works in debug and release mode. try this on a physical device and see if it makes any difference. 

as for the apk size, you will probably want to build for the architecture you need. the zoom sdk is very big but you can look at this link for suggestion( you might need to fork the repo and change the .aar file) 
[https://devforum.zoom.us/t/when-i-integrate-zoom-sdk-my-app-size-increased-to-80mb/7613/4?u=stntz
](url)

**Comment by PPotlaACR** [comment]
Hi stntz,
   I am getting different an error see the attachment below in release mode
![Screenshot (4)_LI](https://user-images.githubusercontent.com/43574666/82161049-4a3a6700-98b7-11ea-9c36-bbf56b01fd51.jpg)
I am using below architectures and AndroidLinkMode
![Screenshot (5)](https://user-images.githubusercontent.com/43574666/82161161-0d22a480-98b8-11ea-81c0-64d4ca339af4.png)

**Comment by stntz** [comment]
try a few different options with the android settings, make sure to clean your output folders and possibly disable the r8 shrinker. I can't replicate this issue... attach a repro if you want or pull the samples folder again

**Comment by stntz** [comment]
[https://forums.xamarin.com/discussion/175824/r8-enabled-gives-build-error-compilation-cant-be-completed-because-some-library-classes-ar](url)

read that and try the workaround in there, looks like a common issue along the xamarin android setup.
