### ISSUE TITLE
How to get list of schedule meetings?

### ISSUE THREAD

**Issue by PPotlaACR** [stntz/Xamarin.ZoomBinding#3]
Hi stntz ,
 I am using below line of code to get the list of meetings
    "MobileRTCSDKError mobileRTCSDKError = zoomSDK.PreMeetingService.ListMeeting();"
But how to get a meeting ids above one is not returning the list of meetings id's

Thanks in Advance

**Comment by stntz** [comment]
you will need to extend MobileRTCPremeetingDelegate and override SinkListMeeting and the result should be in that array and pass that delagate to the premeetingservice

if you check the documentation on zoom, the methods should not be too different.

**Comment by PPotlaACR** [comment]
Could please share sample code base in the comment.

**Comment by PPotlaACR** [comment]
Hi stntz , 
 I tried to extend MobileRTCPremeetingDelegate but not getting success. Could you please share the codebase to do it.
Thanks in Advance

**Comment by stntz** [comment]
Let me see if I can write something out. I see you are on the iOS SDK now. were you able to resolve the issue you had with the android sdk?

PS: the iOS sdk only works for device not simulator

**Comment by PPotlaACR** [comment]
Yes , For android working fine.

**Comment by stntz** [comment]
Hi @PPotlaACR, did you manage to get that working? I have been busy with other works.

**Comment by pranaykumarkolluri** [comment]
Hi Stntz, No , not yet

**Comment by stntz** [comment]
`static TaskCompletionSource<object> meetingListSource;
        public Task<object> ListMeeting()
        {
            if (IsInitialized())
            {
                if (meetingListSource != null)
                    return null;

                meetingListSource = new TaskCompletionSource<object>();

                var premeetingService = mobileRTC.GetPreMeetingService();
                premeetingService.Delegate = new MobilePreDelegate();

                _ = premeetingService.ListMeeting;

                return meetingListSource.Task;
            }
            return null;
        }`

`class MobilePreDelegate : MobileRTCPremeetingDelegate
        {
            public override void SinkDeleteMeeting(PreMeetingError result)
            {
                throw new NotImplementedException();
            }

            public override void SinkEditMeeting(PreMeetingError result, ulong uniquedID)
            {
                throw new NotImplementedException();
            }

            public override void SinkListMeeting(PreMeetingError result, NSObject[] array)
            {
                if (result != PreMeetingError.Success)
                {
                    meetingListSource?.SetException(new Exception("Failed to Load List"));
                }
                meetingListSource?.SetResult(array);                
            }

            public override void SinkSchedultMeeting(PreMeetingError result, ulong uniquedID)
            {
                throw new NotImplementedException();
            }
        }`

@PPotlaACR I am now going to close this. this is how I would go about it.
