### ISSUE TITLE
Missing ZoomUIService in Android sdk

### ISSUE THREAD

**Issue by AdamDiament** [stntz/Xamarin.ZoomBinding#30]
I'm working from the xamarin5 branch

The ZoomSDK is supposed to have a reference via an instance method to an instance of an interface called ZoomUIService, which has a bunch of useful helper methods including enabling picture in picture mode, which is what I am after.

Here's the SDK documentation https://marketplacefront.zoom.us/sdk/meeting/android/us/zoom/sdk/ZoomUIService.html#enableMinimizeMeeting-boolean-
Here's a screenshot of it existing in java 
![image](https://user-images.githubusercontent.com/6513834/141008756-16c54239-228c-4425-a7a8-dff9cedc5df2.png)

I've tried adding the following two lines to metadata.xml

    <attr path="/api/package[@name='us.zoom.sdk']/interface[@name='ZoomUIService']" name="visibility">public</attr>
    <attr path="/api/package[@name='us.zoom.sdk']/class[@name='ZoomSDK']/method[@name='getZoomUIService']" name="visibility">public</attr>

I found some build warnings saying that the build is invalidating the whole type due to "some of its methods were invalid"
Here's the relevant section from my build output.

```
2>C:\projects\Xamarin.ZoomBinding\src\MobileRTC_Droid\obj\Release\api.xml(260131,10):

 warning BG8801: Invalid parameter type 'us.zoom.sdk.ZoomUIDelegate' for member 'US.Zoom.Sdk.IZoomUIService.SetZoomUIDelegate (US.Zoom.Sdk.IZoomUIDelegate)'.

2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Bindings.Core.targets(53,5): obj\Release\api.xml(260131,10)

 warning BG8801: Invalid parameter type 'us.zoom.sdk.ZoomUIDelegate' for member 'US.Zoom.Sdk.IZoomUIService.SetZoomUIDelegate (US.Zoom.Sdk.IZoomUIDelegate)'.

2>C:\projects\Xamarin.ZoomBinding\src\MobileRTC_Droid\obj\Release\api.xml(260085,6): 

warning BG8503: Invalidating 'US.Zoom.Sdk.IZoomUIService' and all its nested types because some of its methods were invalid.

2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Bindings.Core.targets(53,5): obj\Release\api.xml(260085,6) 

warning BG8503: Invalidating 'US.Zoom.Sdk.IZoomUIService' and all its nested types because some of its methods were invalid.

2>C:\projects\Xamarin.ZoomBinding\src\MobileRTC_Droid\obj\Release\api.xml(259458,8): 

warning BG8701: Invalid return type 'us.zoom.sdk.ZoomUIService' for member 'US.Zoom.Sdk.ZoomSDK'.
```

**Comment by stntz** [comment]
I am just looking into this actually, as I have another app that I built off this that could not pick up the MeetingActivity from the sdk. I had this the last time too. will keep you posted. thanks for sharing your findings

**Comment by AdamDiament** [comment]
Adding this line to metadata fixes it:

	<remove-node path="/api/package[@name='us.zoom.sdk']/interface[@name='ZoomUIService']/method[@name='setZoomUIDelegate']"/>

![image](https://user-images.githubusercontent.com/6513834/141010770-79af0b3e-68ba-43f9-81e7-37d91ca8f0ff.png)

**Comment by AdamDiament** [comment]
Want me to raise a PR or leave it to you?

**Comment by stntz** [comment]
Feel free to raise a PR for this. however, that did not reveal the MeetingActivity class. we can get this in for now.
Thanks for the hard work on this
