### ISSUE TITLE
Could you make NuGet package compatible version 8.0, 8.1, 9.0, 10.0 ?

### ISSUE THREAD

**Issue by pranaykumarkolluri** [stntz/Xamarin.ZoomBinding#4]
Currently, Package compatible with  only  version 10.0

**Comment by stntz** [comment]
The minimum I can do is 9.0 as that’s what AndroidX supports. 
This sdk is only AndroidX from Zoom and as they migrate to GCM encryption, this is the only supported version.

The nuget version is 10.0 but the one in this repo has been changed to support 9.0. 
You can clone the repo pending when I make the change to nuget as I am trying to setup a pipeline for auto push to nuget.
