### ISSUE TITLE
Build times

### ISSUE THREAD

**Issue by GFOX91** [stntz/Xamarin.ZoomBinding#5]
Hi,

This is a fantastic solution for Xamarin forms works a treat great job so far!

The only thing I have noticed is build times are considerably slower upon implementation of this solution. Have you experienced this? If so do you have any tips for optimisation?

Thanks,

**Comment by stntz** [comment]
@GFOX91 If you reference the project directly, you might be experiencing an issue where all the dependencies are being built again.
You can try building the binding projects and reference the dll directly.
Would you prefer to have the libraries available on Nuget for both iOS and Android?

**Comment by GFOX91** [comment]
@stntz  I have not referenced the project directly. I have set up a new project following your sample and used the nuget package to get the android working, but am having issues with build speed upon deployment. 

The plan going forward is to also having this working for IOS so a library for this would be ideal. Would this be set up in a different nuget package or added to the current one?

**Comment by stntz** [comment]
@GFOX91 I am going to try and put in the same nuget package. once i have finished understanding how to target different profiles and os from the same package.
The android and iOS project in the repo have the latest sdk from zoom for their gcm encryption update.

only the first build is slow for me really even with the project building dependencies.
You might want to check your build settings

**Comment by GFOX91** [comment]
@stntz  Thanks, I'll take a look at my build settings see if I can optimize anything
