### ISSUE TITLE
Poll's option feature is not showing 

### ISSUE THREAD

**Issue by PPotlaACR** [stntz/Xamarin.ZoomBinding#6]
When I am login as a host using the pro account. the poll option feature is not showing on mobile.
The poll feature that already enables account level. Thanks in advance.

**Comment by stntz** [comment]
ios or android?

**Comment by PPotlaACR** [comment]
Currently, I am checking in android.

**Comment by stntz** [comment]
You cannot start poll from the mobile as a host. either in the Zoom Client or SDK.
Please check the zoom forum or documentation.

[https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-meetings](url)
