### ISSUE TITLE
unable to build the project

### ISSUE THREAD

**Issue by uday-lucky** [stntz/Xamarin.ZoomBinding#7]
HI , i tried to build and deploy your project but after fixing  errors i am unable to fix this?

Xamarin.ZoomBinding-master/src/MobileRTC_Droid/Additions/MMBuddyItemComparator.cs(88,88): Error CS1503: Argument 2: cannot convert from 'Com.Zipow.Videobox.View.MM.MMContentSearchFilesAdapter.ContentFileComparator' to 'Java.Interop.IJavaPeerable' (CS1503) (MobileRTC_Droid)

**Comment by uday-lucky** [comment]
i consumed xamarin.android.zoom nuget and its working fine. looking for ios nuget ? i couldn't find :(

**Comment by stntz** [comment]
Duplicate of #8

**Comment by stntz** [comment]
@uday-lucky 

[https://github.com/stntz/Xamarin.ZoomBinding/issues/8#issuecomment-641510731](url)
