### ISSUE TITLE
Nuget package for ios

### ISSUE THREAD

**Issue by GFOX91** [stntz/Xamarin.ZoomBinding#8]
Hello, I've been using the package to implement zoom via my xamarin app for android. 

I was just wondering what the plans are in terms of completing the Ios bindings and whether you are going to upload them as a separate nuget package specifically for Ios or add them to the current nuget package to cover both Ios and android and what the timescales on this may be?

Really appreciate the work you have done so far. Thanks.

**Comment by stntz** [comment]
Hi @GFOX91 , I was going to bundle both iOS and Android in the same nuget but I am having issues with it and file size for android is already massive. 
It would have meant a new nuget package anyway considering the current package id has android in its name.
I have decided to create a separate iOS nuget. and should be up in a couple of days.
I see you forked the repo. were you able to get the ios binding working in your project?

**Comment by GFOX91** [comment]
Hi @stntz,
The separate package for the ios sounds like the best way to go. No we havent managed to get the ios side of things working yet.

Thanks

**Comment by stntz** [comment]
Hi @GFOX91 

Nuget for iOS
[https://www.nuget.org/packages/Xamarin.iOS.Zoom/](url)

Nuget for iOS ScreenShare
[https://www.nuget.org/packages/Xamarin.iOS.Zoom.ScreenShare/](url)

let me know if you have any issues with this.
