### ISSUE TITLE
Application group identifier group.us.zoom error

### ISSUE THREAD

**Issue by conor-codes** [stntz/Xamarin.ZoomBinding#9]
Hello i was wondering if you could help me with the following, I'm implementing the iOS nuget package and came across the following error:

_Cannot retrieve the container URL for the application group identifier group.us.zoom. Make sure that it has been added to the `com.apple.security.application-groups` entitlement._

It seems to be related to the following: https://devforum.zoom.us/t/having-crash-while-starting-zoom-class/6736/4

I know it's not possible to add the zoom group id to my entitlements,  Is there a property I can access to change the group name to my own ? 

Thanks

**Comment by stntz** [comment]
@conor-codes have you done this in your sdk initialization?
```
 //Only if you are using screen sharing (Broadcast Upload Extension)
mobileRTC.SetAppGroupsName("group.com.syndew.zoomdemo");
```

and this in extension

```
https://github.com/stntz/Xamarin.ZoomBinding/blob/master/samples/ZoomDemoScreenShare/SampleHandler.cs
```

**Comment by conor-codes** [comment]
@stntz i thought the error i was getting was to do with this, it was a red herring though. I wasn't using the screen share functionality but the application was crashing because I had not added the request permissions, microphone, video etc.

**Comment by stntz** [comment]
@conor-codes yeah.. that happens. can I close this now?

**Comment by conor-codes** [comment]
@stntz yeah cheers
